### PR TITLE
Use new 'Manage taxonomies' permission

### PR DESCRIPTION
**Pull request by laulaz**
Permission is by default assigned to Manager and Site Administrator roles
This refs #134

### CODE REVIEW

**Review by petschki — APPROVED** [review]
LGTM

**Comment by laulaz** [comment]
@petschki could you please review this again?  🙏

**Review by petschki — CHANGES_REQUESTED** [review]
The new `icon_expr` string `puzzle` only works in Plone 6 with Bootstrap 5. Sorry for the wrong suggestion before. Either this package registers a separate Plone 6 profile with the action definition or we bump the version to a  major version in a newPR and support Plone 6 only from that point on.

Second suggestion would be my favorite.

**Comment by laulaz** [comment]
@petschki could you merge this ?

**Pull request merged**
