### PR TITLE
Plone 6 updates

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by laulaz** [comment]
@petschki splitting the commits into 2 releases "breaks" the upgrade step :stuck_out_tongue_closed_eyes:

**Comment by petschki** [comment]
> @petschki splitting the commits into 2 releases "breaks" the upgrade step 😝

gosh ... I'll fix that in the new `2.x` branch and make a new release `2.2.3`

**Comment by laulaz** [comment]
> gosh ... I'll fix that in the new `2.x` branch and make a new release `2.2.3`
the `2.2.2` release & branch are good, don't worry 👍 
The problem is for the next version : we need to declare a new upgrade step & version profile (the old step was just updated by a new commit).

**Comment by petschki** [comment]
> > gosh ... I'll fix that in the new `2.x` branch and make a new release `2.2.3`
> 
> the `2.2.2` release & branch are good, don't worry 👍 The problem is for the next version : we need to declare a new upgrade step & version profile (the old step was just updated by a new commit).

I think the upgradestep will break the 5.2 configlet because it places `puzzle` into `icon_expr` ... I'll bump the profile version here up to `2000` and re-target the upgradestep for the configlet.

**Comment by laulaz** [comment]
> I think the upgradestep will break the 5.2 configlet because it places `puzzle` into `icon_expr` ... 
`puzzle` is not updated is not in the `2.2.2` branch (only permission is) :+1 
https://github.com/collective/collective.taxonomy/blob/2.x/src/collective/taxonomy/profiles/default/controlpanel.xml

**Comment by laulaz** [comment]
@petschki we should clarify the branches / versions compatibility in README, but otherwise, LGTM 👍

**Pull request merged**
