### PR TITLE
Remove cypress videos from repo / output PyPI egg

### PR DESCRIPTION
**Pull request by avoinea**
See #116

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
This is good, but I wonder if cypress should be removed completely from the released egg... Isn't it just for testing?

**Review by petschki — CHANGES_REQUESTED** [review]
The video is linked here: https://github.com/collective/collective.taxonomy/blob/master/docs/tutorial.md ... I'd remove the whole paragraph with the video there.

**Comment by avoinea** [comment]
> This is good, but I wonder if cypress should be removed completely from the released egg... Isn't it just for testing?

True. Fixed.

**Comment by avoinea** [comment]
> The video is linked here: https://github.com/collective/collective.taxonomy/blob/master/docs/tutorial.md ... I'd remove the whole paragraph with the video there.

@petschki Removed.

**Review by petschki — APPROVED** [review]
LGTM

**Pull request merged**
