### PR TITLE
Create taxonomy tutorial

### LINKED ISSUE #87: Improve docs
Need a end user documentation showing how to:

* Use the package
* Generate the taxonomy behavior
* Put some data
* And use it

(the cypress test will generate a movie in the end with all the steps, we can link it in the README)

### PR DESCRIPTION
**Pull request by rodfersou**
closes #87

### CODE REVIEW

**Comment by rodfersou** [comment]
@petschki please take a look now

**Comment by rodfersou** [comment]
@petschki  you think we can remove this from the README:

image

when merge this PR?

**Comment by petschki** [comment]
> @petschki you think we can remove this from the README:
> 
> image
> 
> when merge this PR?

yes, please remove this.

**Comment by petschki** [comment]
when done and merged, I'll release 2.0.1 ... got the permissions today.

**Pull request merged**
