### PR TITLE
Add possibility to change option ids 

### LINKED ISSUE #72: Add possibility to change option id/value
Right now the option ids are auto-generated and that's not user-friendly when using with eea.facetednavigation for example.

Would be nice to be able to edit these ids via the interface.

### PR DESCRIPTION
**Pull request by Petchesi-Iulian**
Fixes #72 , WIP

### CODE REVIEW

**Review by alecghica — CHANGES_REQUESTED** [review]
* The term identifier should be unique so the editing interface should not allow to create duplicates.
* The "Edit taxonomy data" user interface should be updated to make it more user friendly.
* Documentation should be updated.

**Comment by alecghica** [comment]
FYI: a distinct PR will be open soon in order to provide a REST API endpoint to fully integrate into the Plone6 frontend (Volto) control panel. This PR will basically merge the work already done under [eea.api.taxonomy](https://github.com/eea/eea.api.taxonomy) and [volto-taxonomy](https://github.com/eea/volto-taxonomy).

**Comment by Petchesi-Iulian** [comment]
There is currently an issue with cypress and the har-validator module, more info here: https://github.com/cypress-io/cypress/issues/19102

As a quickfix I added har-validator in package.json

**Review by avoinea — APPROVED** [review]
LGTM.

**Review by alecghica — APPROVED** [review]
I also checked it and looks fine. The tutorial was also updated to catch with the changes made to the UI.

**Pull request merged**
