### PR TITLE
Fix editor save to work on Plone 5

### PR DESCRIPTION
**Pull request by datakurre**
Minimal changes to make editor save on Plone 5

Not so pretty changes, but made it work

### CODE REVIEW

**Comment by tomgross** [comment]
@datakurre Saving works, but there is still the red statusbar "error
    Changes have been made but you have to click on submit button to save these changes." in the taxonomy controlpanel

**Comment by datakurre** [comment]
@tomgross Does it work without that message on Plone 4?

**Comment by cedricmessiant** [comment]
Thanks @datakurre.
I haven't tested it in Plone 5 but in Plone 4, this message disappear after save. Well, it should disappear but it doesn't seem to do so anymore. @tomgross : I merge this pull request and then I will fix the bug.

**Comment by cedricmessiant** [comment]
well, I had to fix this commit finally ( 77ed72f ). Everything works as expected with Plone 4 now. @tomgross If you still have an error, don't hesitate to open an issue).

**Pull request merged**
