### PR TITLE
Change @@taxonomy-edit-data view

### PR DESCRIPTION
**Pull request by cedricmessiant**
Now uses a React/Redux app to edit taxonomy data. It is now possible to edit this data in multiple languages and to compare between languages.

See the preview of this view in the README.

### CODE REVIEW

**Comment by vincentfretin** [comment]
Wahou, this was a lot of work.
The animated gif is awesome
https://github.com/cedricmessiant/collective.taxonomy/blob/04303d3588fe4109906179bfda87bcad59d8b159/images/edit_taxonomy_data.gif
This is big plus over the old implementation.

@cedricmessiant  If someone want to test this, he (she) need to execute

    npm install
    npm run build

right? I think we can commit the generated bundle after the PR is merged.

**Comment by tomgross** [comment]
Thanks @cedricmessiant for your effort. I started using your work for the Plone 5 port of the package in https://github.com/tomgross/collective.taxonomy. Unfortunally the lasted version (04303d3) of your fork throws a JavaScript error (on the included Plone 4.3 buildout) and editing data does not work. See attached screenshot: 
c taxonomy-error

**Comment by tomgross** [comment]
This is the error in debug mode: 
c taxonomy-error-debug

The site is single language english

**Comment by tomgross** [comment]
Changing the language of the test vocabulary from "DK" to "EN" shows the data-edit view as expected.

**Comment by cedricmessiant** [comment]
I see. It's because you need DK in `portal_languages` supported languages
Maybe, I should add the taxonomy's default language to the mapping even if it is not in `portal_languages`

**Comment by bsuttor** [comment]
Thank you for the contribution,

I try it and it works fine for me, 
Could we merge it and then release it ?

**Comment by cedricmessiant** [comment]
Thanks !

**Pull request merged**
